### PR TITLE
Catch all exception occurred during CassadraClient#connect call 

### LINKED ISSUE #21: NoHostAvailableException during cassandraClient.connect leads to failure in Future.fail()
```
        try {
            client = client.connect(CASSANDRA_KEYSPACE) { ar ->
                if (ar.failed()) {
                    logger.error("ALL IS BAD....")
                    startFuture.fail(ar.cause())
                } else {
                    repository = Repository(client)

                    vertx.eventBus().consumer<JsonObject>(ADDRESS, this::handle)
                    startFuture.complete()
                }
            }
        } catch (e: Exception) {
            logger.warn("catched exception")
            startFuture.fail(e)
        }
```

The above code leads to an exception, if no cassandra server is available (NoHostAvailableException). This exception is catched in the given catch block. If startFuture.complete() is called, all is fine (well, then the verticle is deployed, even though it shouldn't), but if startFuture.fail(e) is called, the event is not fetched in my MainVerticle.

### PR DESCRIPTION
**Pull request by Sammers21**
Fixes #21

### CODE REVIEW

**Comment by tsegismont** [comment]
@Sammers21 do we need this as it seems #21 fixed by #16 ?

**Comment by Sammers21** [comment]
@tsegismont , #21 consist of 2 parts:

1. If there is no host, an exception is thrown on `connectAsync` call. We need catch it 
2. Unable to undeploy a verticle with CassandraClient

This PR solves the first one. Second one is adressed in #16.

**Comment by tsegismont** [comment]
Thanks for clarifying @Sammers21

**Comment by tsegismont** [comment]
@Sammers21 when you'll merge this one, could you please also:

- backport the fix to the 3.6 branch
- update the [3.6.3](https://github.com/vert-x3/issues/issues/435) umbrella issue

Thank you

**Pull request merged**
